# Generated by Django 4.1.3 on 2022-11-15 18:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=40)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/logos')),
                ('avg_rating', models.FloatField(blank=True, default=0.0, null=True)),
                ('num_ratings', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('salary_h', models.DecimalField(decimal_places=2, max_digits=6)),
                ('hours_per_week', models.IntegerField()),
                ('role', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('years_xp', models.CharField(choices=[('0-3 anos', 'Zero A Tres'), ('3-5 anos', 'Tres A Cinco'), ('5-10 anos', 'Cinco A Dez'), ('10+ anos', 'Dez Ou Mais')], max_length=20)),
                ('work_model', models.CharField(choices=[('Remoto', 'Remoto'), ('Presencial', 'Presencial'), ('Híbrido', 'Hibrido')], default='Presencial', max_length=10)),
                ('contract_type', models.CharField(choices=[('Tempo inteiro', 'Tempo Inteiro'), ('Meia jornada', 'Meia Jornada'), ('Estágio', 'Estagio')], default='Tempo inteiro', max_length=20)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('date_expires', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('fav_companies', models.ManyToManyField(db_table='app_user_fav_companies', to='app.company')),
                ('fav_offers', models.ManyToManyField(db_table='app_user_fav_offers', to='app.offer')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('time', models.TimeField(auto_now=datetime.datetime(2022, 11, 15, 18, 15, 32, 228737))),
                ('text', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
