# Generated by Django 4.1.3 on 2022-12-27 23:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_comment_time_alter_company_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.TimeField(auto_now=datetime.datetime(2022, 12, 27, 23, 30, 43, 384626)),
        ),
    ]
