# Generated by Django 4.1.3 on 2022-12-28 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_comment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.TimeField(auto_now=datetime.datetime(2022, 12, 28, 17, 15, 48, 209228)),
        ),
    ]
