# Generated by Django 4.1.3 on 2022-12-28 23:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_profile_pic_alter_comment_time_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.TimeField(auto_now=datetime.datetime(2022, 12, 28, 23, 10, 12, 976194)),
        ),
        migrations.AlterField(
            model_name='reply',
            name='time',
            field=models.TimeField(auto_now=datetime.datetime(2022, 12, 28, 23, 10, 12, 976487)),
        ),
    ]
